import type { BalanceConfig } from './types';

export const BALANCE: BalanceConfig = {
  player: {
    maxHealth: 100,
    maxArmor: 100,
    startingArmor: 25,
    walkSpeed: 5.2,
    sprintMult: 1.55,
    crouchMult: 0.55,
    jumpVelocity: 7.2,
    gravity: 22,
    staminaMax: 100,
    staminaDrainPerSec: 22,
    staminaRegenPerSec: 18,
    staminaJumpCost: 12,
    eyeHeight: 1.7,
    crouchEyeHeight: 1.05,
    radius: 0.4,
    armorAbsorb: 0.66,
    respawnInvulnSec: 2.0,
  },
  progression: {
    xpBase: 100,
    xpGrowth: 1.22,
    comboWindow: 4.0,
    comboMaxMult: 5.0,
    comboPerKill: 0.1,
    killStreakThresholds: [5, 10, 25, 50, 100],
    upgradeChoices: 3,
    rarityWeights: { common: 100, rare: 40, epic: 12 },
  },
  enemyScaling: {
    hpPerWave: 0.10,
    hpGrowth: 1.035,
    damagePerWave: 0.06,
    speedPerWave: 0.015,
    speedCap: 1.5,
    eliteHpMult: 2.6,
    eliteDamageMult: 1.5,
    eliteScale: 1.25,
    bossHpPerBossNumber: 0.5,
  },
  economy: {
    ammoPrice: 75,
    armorPrice: 100,
    healthPrice: 100,
    dropChance: 0.28,
  },
  waves: {
    baseBudget: 60,
    budgetPerWave: 22,
    budgetGrowth: 1.06,
    bossEvery: 5,
    breakDuration: 22,
    spawnBatchSize: 6,
    spawnBatchInterval: 1.6,
    minSpawnDistance: 18,
    maxSpawnDistance: 48,
    playerFovAvoidDeg: 70,
    perfBudgetMin: 0.85,
    perfBudgetMax: 1.25,
  },
};
