import type { EnemyConfig } from './types';

/**
 * Enemy roster. To add an enemy: append an entry with a unique id; set
 * minWave/cost/weight so the wave generator can budget it. The renderer keys
 * an InstancedMesh batch off `shape` + `color` + `scale` automatically.
 * See README "How to add a new enemy".
 */
export const ENEMIES: EnemyConfig[] = [
  {
    id: 'rusher',
    name: 'Husk',
    role: 'melee',
    hp: 60,
    speed: 4.2,
    accel: 14,
    radius: 0.45,
    height: 1.8,
    damage: 12,
    attackRange: 1.7,
    attackCooldown: 1.1,
    attackWindup: 0.35,
    aggroRange: 70,
    xp: 10,
    score: 100,
    currencyMin: 2,
    currencyMax: 6,
    color: 0x9c3c2e,
    scale: 1.0,
    shape: 'capsule',
    headshotZone: 0.25,
    minWave: 1,
    cost: 10,
    weight: 100,
  },
  {
    id: 'crawler',
    name: 'Skitter',
    role: 'melee',
    hp: 28,
    speed: 7.0,
    accel: 26,
    radius: 0.38,
    height: 0.8,
    damage: 8,
    attackRange: 1.4,
    attackCooldown: 0.8,
    attackWindup: 0.2,
    aggroRange: 80,
    xp: 8,
    score: 80,
    currencyMin: 1,
    currencyMax: 4,
    color: 0xb8862d,
    scale: 0.7,
    shape: 'sphere',
    headshotZone: 0.35,
    minWave: 2,
    cost: 7,
    weight: 80,
  },
  {
    id: 'tank',
    name: 'Brute',
    role: 'melee',
    hp: 420,
    speed: 1.9,
    accel: 6,
    radius: 0.85,
    height: 2.6,
    damage: 34,
    attackRange: 2.4,
    attackCooldown: 2.0,
    attackWindup: 0.7,
    aggroRange: 70,
    xp: 45,
    score: 450,
    currencyMin: 12,
    currencyMax: 25,
    color: 0x5d2f6e,
    scale: 1.6,
    shape: 'box',
    headshotZone: 0.18,
    minWave: 4,
    cost: 45,
    weight: 35,
  },
  {
    id: 'spitter',
    name: 'Lobber',
    role: 'ranged',
    hp: 55,
    speed: 3.0,
    accel: 10,
    radius: 0.45,
    height: 1.7,
    damage: 0,
    attackRange: 26,
    attackCooldown: 2.4,
    attackWindup: 0.6,
    aggroRange: 90,
    preferredRange: 18,
    projectile: { speed: 16, radius: 0.25, damage: 14, color: 0x86e83c },
    xp: 14,
    score: 150,
    currencyMin: 3,
    currencyMax: 8,
    color: 0x4f7a28,
    scale: 1.0,
    shape: 'cone',
    headshotZone: 0.25,
    minWave: 3,
    cost: 16,
    weight: 55,
  },
  {
    id: 'exploder',
    name: 'Blister',
    role: 'exploder',
    hp: 40,
    speed: 5.2,
    accel: 18,
    radius: 0.5,
    height: 1.5,
    damage: 0,
    attackRange: 2.2,
    attackCooldown: 99,
    attackWindup: 0.5,
    aggroRange: 85,
    explode: { radius: 4.5, damage: 38, fuse: 0.55 },
    xp: 12,
    score: 120,
    currencyMin: 2,
    currencyMax: 6,
    color: 0xd8642a,
    scale: 1.05,
    shape: 'sphere',
    headshotZone: 0.3,
    minWave: 4,
    cost: 14,
    weight: 45,
  },
  {
    id: 'warden',
    name: 'Warden',
    role: 'melee',
    hp: 150,
    speed: 2.6,
    accel: 9,
    radius: 0.55,
    height: 2.0,
    damage: 20,
    attackRange: 2.0,
    attackCooldown: 1.5,
    attackWindup: 0.5,
    aggroRange: 70,
    shield: { hp: 220, arcDeg: 110 },
    xp: 28,
    score: 300,
    currencyMin: 8,
    currencyMax: 16,
    color: 0x2e5e8c,
    scale: 1.2,
    shape: 'box',
    headshotZone: 0.2,
    minWave: 6,
    cost: 30,
    weight: 35,
  },
  {
    id: 'shaman',
    name: 'Thurible',
    role: 'support',
    hp: 90,
    speed: 2.8,
    accel: 9,
    radius: 0.5,
    height: 1.9,
    damage: 6,
    attackRange: 2.0,
    attackCooldown: 2.0,
    attackWindup: 0.5,
    aggroRange: 75,
    preferredRange: 14,
    aura: { radius: 9, healPerSec: 8, speedMult: 1.25 },
    xp: 30,
    score: 350,
    currencyMin: 10,
    currencyMax: 18,
    color: 0x3ec9a7,
    scale: 1.1,
    shape: 'crystal',
    headshotZone: 0.25,
    minWave: 7,
    cost: 32,
    weight: 28,
  },
  {
    id: 'boss-colossus',
    name: 'The Colossus',
    role: 'boss',
    hp: 4200,
    speed: 2.2,
    accel: 7,
    radius: 1.6,
    height: 4.6,
    damage: 50,
    attackRange: 3.8,
    attackCooldown: 2.6,
    attackWindup: 0.9,
    aggroRange: 999,
    boss: {
      phases: [
        { untilHpFraction: 0.66, speedMult: 1.0, attacks: ['slam'], attackCooldown: 4.0 },
        { untilHpFraction: 0.33, speedMult: 1.25, attacks: ['slam', 'barrage'], attackCooldown: 3.2 },
        { untilHpFraction: 0.0, speedMult: 1.5, attacks: ['slam', 'barrage', 'summon', 'charge'], attackCooldown: 2.4 },
      ],
      weakPointRadius: 0.55,
      weakPointMult: 3.0,
      summons: 'crawler',
    },
    projectile: { speed: 20, radius: 0.35, damage: 18, color: 0xff4d6b },
    xp: 400,
    score: 5000,
    currencyMin: 150,
    currencyMax: 250,
    color: 0x8c1f3d,
    scale: 2.6,
    shape: 'box',
    headshotZone: 0.12,
    minWave: 5,
    cost: 0, // never budget-picked; spawned by boss waves explicitly
    weight: 0,
  },
];

export const enemyById = (id: string): EnemyConfig | undefined =>
  ENEMIES.find((e) => e.id === id);

export const BOSS_ID = 'boss-colossus';
