import type { WeaponConfig } from './types';

/**
 * Weapon balance lives here. To add a weapon: append an entry, give it a free
 * `slot`, and it appears in the loadout, shop, and validation automatically.
 * See README "How to add a new weapon".
 */
export const WEAPONS: WeaponConfig[] = [
  {
    id: 'machete',
    name: 'Machete',
    slot: 0,
    description: 'Standard-issue fallback. Never runs dry.',
    kind: 'melee',
    auto: true,
    damage: 55,
    pellets: 1,
    headshotMult: 1.0,
    rpm: 80,
    spreadDeg: 0,
    bloomPerShot: 0,
    bloomMaxDeg: 0,
    recoilPitchDeg: 0.8,
    recoilYawDeg: 0.5,
    fireTrauma: 0.07,
    magSize: 0,
    reserveMax: 0,
    startingReserve: 0,
    reloadTime: 0.1,
    range: 2.6,
    falloffStart: 2.6,
    falloffMinMult: 1,
    pierce: 0,
    tracerColor: 0xdddddd,
    muzzleColor: 0xdddddd,
    fireSound: 'melee-swing',
    reloadSound: 'reload-light',
    upgrades: [],
    unlockCost: 0,
    unlockedByDefault: true,
    melee: { range: 2.6, arcDeg: 110, knockback: 9 },
  },
  {
    id: 'pistol',
    name: 'P-9 Sidearm',
    slot: 1,
    description: 'Reliable semi-auto. Infinite-feeling reserve, honest damage.',
    kind: 'hitscan',
    auto: false,
    damage: 22,
    pellets: 1,
    headshotMult: 2.0,
    rpm: 320,
    spreadDeg: 0.7,
    bloomPerShot: 0.25,
    bloomMaxDeg: 2.2,
    recoilPitchDeg: 0.85,
    fireTrauma: 0.03,
    recoilYawDeg: 0.25,
    magSize: 15,
    reserveMax: 240,
    startingReserve: 90,
    reloadTime: 1.1,
    range: 80,
    falloffStart: 30,
    falloffMinMult: 0.5,
    pierce: 0,
    tracerColor: 0xffd27a,
    muzzleColor: 0xffc46b,
    fireSound: 'pistol-fire',
    reloadSound: 'reload-light',
    upgrades: [
      { cost: 150, damageMult: 1.2, label: 'Match-grade barrel (+20% dmg)' },
      { cost: 300, rpmMult: 1.25, label: 'Lightened trigger (+25% fire rate)' },
      { cost: 500, magBonus: 6, damageMult: 1.15, label: 'Extended mag +6, +15% dmg' },
    ],
    unlockCost: 0,
    unlockedByDefault: true,
  },
  {
    id: 'shotgun',
    name: 'M870 Breacher',
    slot: 2,
    description: '8-pellet pump. Deletes anything inside hugging distance.',
    kind: 'hitscan',
    auto: false,
    damage: 11,
    pellets: 8,
    headshotMult: 1.6,
    rpm: 68,
    spreadDeg: 4.6,
    bloomPerShot: 0.4,
    bloomMaxDeg: 6.5,
    recoilPitchDeg: 3.2,
    fireTrauma: 0.16,
    recoilYawDeg: 0.8,
    magSize: 6,
    reserveMax: 90,
    startingReserve: 30,
    reloadTime: 2.2,
    range: 40,
    falloffStart: 8,
    falloffMinMult: 0.25,
    pierce: 0,
    tracerColor: 0xffa64d,
    muzzleColor: 0xff9d3d,
    fireSound: 'shotgun-fire',
    reloadSound: 'reload-shell',
    upgrades: [
      { cost: 250, damageMult: 1.2, label: 'Hot loads (+20% dmg)' },
      { cost: 450, spreadMult: 0.75, label: 'Full choke (-25% spread)' },
      { cost: 700, magBonus: 3, reloadMult: 0.8, label: '+3 shells, faster pump' },
    ],
    unlockCost: 350,
    unlockedByDefault: false,
  },
  {
    id: 'rifle',
    name: 'AR-77 Vanguard',
    slot: 3,
    description: 'Full-auto workhorse. The horde answer for the indecisive.',
    kind: 'hitscan',
    auto: true,
    damage: 16,
    pellets: 1,
    headshotMult: 1.8,
    rpm: 680,
    spreadDeg: 1.1,
    bloomPerShot: 0.14,
    bloomMaxDeg: 3.4,
    recoilPitchDeg: 0.55,
    fireTrauma: 0.05,
    recoilYawDeg: 0.3,
    magSize: 32,
    reserveMax: 360,
    startingReserve: 128,
    reloadTime: 1.7,
    range: 110,
    falloffStart: 45,
    falloffMinMult: 0.55,
    pierce: 0,
    tracerColor: 0x9adcff,
    muzzleColor: 0xa8d8ff,
    fireSound: 'rifle-fire',
    reloadSound: 'reload-mag',
    upgrades: [
      { cost: 300, damageMult: 1.18, label: 'AP rounds (+18% dmg)' },
      { cost: 550, rpmMult: 1.15, spreadMult: 0.85, label: 'Recoil comp (+15% rate, tighter)' },
      { cost: 850, magBonus: 16, label: 'Drum mag +16' },
    ],
    unlockCost: 1000,
    unlockedByDefault: false,
  },
  {
    id: 'sniper',
    name: 'LRX Harbinger',
    slot: 4,
    description: 'Bolt-action lance. Punches through a whole queue of skulls.',
    kind: 'hitscan',
    auto: false,
    damage: 160,
    pellets: 1,
    headshotMult: 2.5,
    rpm: 42,
    spreadDeg: 0.05,
    bloomPerShot: 0.0,
    bloomMaxDeg: 0.5,
    recoilPitchDeg: 4.5,
    fireTrauma: 0.22,
    recoilYawDeg: 0.6,
    magSize: 5,
    reserveMax: 50,
    startingReserve: 20,
    reloadTime: 2.6,
    range: 300,
    falloffStart: 200,
    falloffMinMult: 0.8,
    pierce: 3,
    tracerColor: 0xff5b78,
    muzzleColor: 0xff7088,
    fireSound: 'sniper-fire',
    reloadSound: 'reload-bolt',
    upgrades: [
      { cost: 400, damageMult: 1.25, label: 'Magnum chamber (+25% dmg)' },
      { cost: 700, rpmMult: 1.3, reloadMult: 0.8, label: 'Smooth bolt (+30% cycle)' },
      { cost: 1000, magBonus: 3, damageMult: 1.15, label: '+3 rounds, +15% dmg' },
    ],
    unlockCost: 1500,
    unlockedByDefault: false,
    adsZoom: 3.0,
  },
  {
    id: 'launcher',
    name: 'GL-6 Thumper',
    slot: 5,
    description: 'Arcing grenades. Crowd control measured in body parts.',
    kind: 'projectile',
    auto: false,
    damage: 30, // direct-hit bonus; the blast carries the real payload
    pellets: 1,
    headshotMult: 1.0,
    rpm: 55,
    spreadDeg: 0.4,
    bloomPerShot: 0.2,
    bloomMaxDeg: 2.0,
    recoilPitchDeg: 2.8,
    fireTrauma: 0.18,
    recoilYawDeg: 0.5,
    magSize: 4,
    reserveMax: 36,
    startingReserve: 12,
    reloadTime: 2.8,
    range: 120,
    falloffStart: 120,
    falloffMinMult: 1.0,
    pierce: 0,
    projectile: {
      speed: 28,
      gravity: 14,
      radius: 0.18,
      lifetime: 5,
      explosive: { radius: 5.5, damage: 110 },
    },
    tracerColor: 0xb8ff5e,
    muzzleColor: 0xc8ff7a,
    fireSound: 'launcher-fire',
    reloadSound: 'reload-heavy',
    upgrades: [
      { cost: 500, damageMult: 1.25, label: 'HE filler (+25% blast)' },
      { cost: 800, magBonus: 2, label: '+2 grenades' },
      { cost: 1200, rpmMult: 1.3, reloadMult: 0.75, label: 'Auto-loader' },
    ],
    unlockCost: 2200,
    unlockedByDefault: false,
  },
  {
    id: 'arccaster',
    name: 'XR-0 Arccaster',
    slot: 6,
    description: 'Experimental coil weapon. Bolts chain between targets.',
    kind: 'projectile',
    auto: true,
    damage: 34,
    pellets: 1,
    headshotMult: 1.5,
    rpm: 240,
    spreadDeg: 0.3,
    bloomPerShot: 0.1,
    bloomMaxDeg: 1.5,
    recoilPitchDeg: 0.4,
    fireTrauma: 0.06,
    recoilYawDeg: 0.2,
    magSize: 40,
    reserveMax: 280,
    startingReserve: 120,
    reloadTime: 2.0,
    range: 90,
    falloffStart: 90,
    falloffMinMult: 1.0,
    pierce: 0,
    projectile: {
      speed: 70,
      gravity: 0,
      radius: 0.12,
      lifetime: 2,
      chain: { count: 3, range: 7, damageMult: 0.6 },
    },
    tracerColor: 0x7af2ff,
    muzzleColor: 0x8df5ff,
    fireSound: 'arc-fire',
    reloadSound: 'reload-cell',
    upgrades: [
      { cost: 600, damageMult: 1.2, label: 'Overvolted coils (+20% dmg)' },
      { cost: 950, label: 'Longer arcs (+chain via dmg retention)', damageMult: 1.1, rpmMult: 1.1 },
      { cost: 1400, magBonus: 20, rpmMult: 1.15, label: 'Capacitor bank' },
    ],
    unlockCost: 3000,
    unlockedByDefault: false,
  },
];

export const weaponById = (id: string): WeaponConfig | undefined =>
  WEAPONS.find((w) => w.id === id);
